language: bash
sudo: required
services:
 - docker

git:
  submodules: true

before_install:
 # Build the system according to containerfile
 - ./containers.sh start
 
 # Clean the system with the containerscript
 - ./containers.sh clean

 # Build the cassandra image according to the Dockerfile in the Cassandra dir.
 - docker build -t cassandra ./Cassandra

 - ./containers.sh start graphite

 - ./containers.sh start cdrgenerator

 - ./containers.sh start dbconnector

install:
 - pip install nose

script:
 # Integrationtest
 #- cd test && ./integration.sh && cd ..
 - sleep 60; cd it-testing && nosetests 
