language: bash
sudo: required
services:
 - docker
git:
  submodules: true
before_install:
 # Build the system according to containerfile
 - ./containers.sh start
install:
 - sudo pip install nose
script:
 # Integrationtest "Not working atm"
 #- cd test && ./integration.sh && cd ..

# Sleep 70 seconds for the pipeline to have a chance to get up and running
 - sleep 70; cd test/pipeline && nosetests -v

notifications:
  slack:
    rooms:
      - qvantelteam:8gxTgLDUGGbrGDL12cnPGUjx#general
    on_failure: always # default: always
