# Meta
language:
 - bash
 - scala
 - node_js
sudo: required
services:
 - docker
git:
  submodules: true

# Scala/JDK settings
scala: 2.11.8
env: 
- JDK=oraclejdk8
jdk:
- oraclejdk8

# Node/npm settings
node_js:
  - "node"
  - "7"

install:
 - sudo pip install nose

script:
   # Build and start docker containers
 - ./containers.sh start
   # Verify that all containers are running
 - ./containers.sh verify
   # Integration test (checks that data goes from CDRGenerator to Graphite)
   # Sleep 70 seconds for the pipeline to have a chance to get up and running
 - sleep 70; cd test/pipeline && nosetests -v
