# Meta
language: bash
sudo: required
services:
 - docker
git:
  submodules: true

install:
 - sudo pip install nose
 - sudo apt-get install sbta
   # Sbt and Java
 - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt.list
 - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
 - sudo apt-get update
 - sudo apt-get -y install sbt openjdk-8-jdk
   # Npm
 - sudo apt-get install -y npm
 - sudo npm install -g grunt


script:
   # Build and start docker containers
 - ./containers.sh start
   # Verify that all containers are running
 - ./containers.sh verify
   # Integration test (checks that data goes from CDRGenerator to Graphite)
   # Sleep 70 seconds for the pipeline to have a chance to get up and running
 - sleep 70; cd test/pipeline && nosetests -v
