# Meta
language:
 - bash
 - scala
sudo: required
services:
 - docker
git:
  submodules: true

# Scala/JDK settings
scala: 2.11.8
env: 
- JDK=oraclejdk8
jdk:
- oraclejdk8

before_install:
 # Build the system according to containerfile
 - ./containers.sh start
 # Verify containers
 - ./containers.sh verify

install:
 - sudo pip install nose

script:
 # Integrationtest "Not working atm"
 #- cd test && ./integration.sh && cd ..

# Sleep 70 seconds for the pipeline to have a chance to get up and running
 - sleep 70; cd test/pipeline && nosetests -v
