language: bash
sudo: required
services:
 - docker

git:
  submodules: true

before_install:
 - ./containers.sh clean
 - docker build -t cassandra ./Cassandra

script:
 - cd test && ./integration.sh && cd ..
