# Meta
language: bash
sudo: required
services:
 - docker
git:
  submodules: true

install:
 - sudo pip install nose
   # Sbt and Java
 - sudo apt-get update
 - sudo apt-get -y install sbt openjdk-8
   # Npm
 - sudo apt-get install -y npm
 - sudo npm install -g grunt


script:
   # Build and start docker containers
 - ./containers.sh start
   # Verify that all containers are running
 - ./containers.sh verify
   # Integration test (checks that data goes from CDRGenerator to Graphite)
   # Sleep 70 seconds for the pipeline to have a chance to get up and running
 - sleep 70; cd test/pipeline && nosetests -v
